server:
  port: 8181
spring:
  application:
    name: seata-storage-service

#server_urls: http://localhost:8200
#service_name: orderfy

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
