server:
  port: 9866 #对应服务的端口号

spring:
  application:
    name: alibaba-sentinel-service # Spring 应用名
  cloud:
    # Sentinel 配置项，对应 SentinelProperties 配置属性类
    sentinel:
      enabled: true # 是否开启。默认为 true 开启
      eager: true # 是否饥饿加载。默认为 false 关闭
      transport:
        dashboard: 127.0.0.1:7070 # Sentinel 控制台地址
      filter:
        url-patterns: /** # 拦截请求的地址。默认为 /*
      # Sentinel 规则的数据源，是一个 Map 类型。key 为数据源名，可自定义；value 为数据源的具体配置
      datasource:
        # 名称随意，这些是dashboard做持久化后添加规则，会在nacos的配置文件中生成该配置(没用可不添加)
        flow:
          # 对应 DataSourcePropertiesConfiguration 类
          nacos:
            server-addr: 127.0.0.1:8848 # Nacos 服务器地址
            namespace: # Nacos 命名空间
            group-id: SENTINEL_GROUP # Nacos 分组
            data-id: ${spring.application.name}-flow-rule # Nacos 配置集编号
            data-type: json # 数据格式
            rule-type: flow # 规则类型
        degrade:
          nacos:
            server-addr: 127.0.0.1:8848 # Nacos 服务器地址
            namespace: # Nacos 命名空间
            group-id: SENTINEL_GROUP # Nacos 分组
            data-id: ${spring.application.name}-degrade-rule # Nacos 配置集编号
            data-type: json # 数据格式
            rule-type: degrade # 规则类
        system:
          nacos:
            server-addr: 127.0.0.1:8848 # Nacos 服务器地址
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            rule-type: system
          authority:
            nacos:
              server-addr: 127.0.0.1:8848 # Nacos 服务器地址
              dataId: ${spring.application.name}-authority-rules
              groupId: SENTINEL_GROUP
              rule-type: authority
          param-flow:
            nacos:
              server-addr: 127.0.0.1:8848 # Nacos 服务器地址
              dataId: ${spring.application.name}-param-flow-rules
              groupId: SENTINEL_GROUP
              rule-type: param-flow



