server:
  port: 8182
spring:
  application:
    name: seata-account-service

server_urls: http://localhost:8200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug

