server:
  port: 8180
spring:
  application:
    name: seata-order-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug

