spring:
  application:
    name: nacos-order-service # Spring 应用名

server:
  port: 8183 # 服务器端口。默认为 8080


# 在配置文件中禁用默认的URLHttpConnection，启动okhttp
feign:
  # 开启okhttp
  okhttp:
    enabled: true
  httpclient:
    connectionTimeout: 5000
    followRedirects: true
  client:
    config:
      default:
        readTimeout: 5000
        writeTimeout: 5000

